### ISSUE TITLE
repo init command fatal message

### ISSUE THREAD

**Issue by salmansheikh** [sifive/freedom-u-sdk#126]
I am trying to run this command in WSL/Ubuntu app in Windows 10.

 repo init -u git://github.com/sifive/meta-sifive -b v201908-branch -m tools/manifests/sifive.xml

But got this error:

gpg: keybox '/home/ssheikh/.repoconfig/gnupg/pubring.kbx' created
gpg: /home/ssheikh/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: key 67B7E448692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2

Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Finding sources: 100% (49/49)
remote: Total 49 (delta 8), reused 49 (delta 8)
Unpacking objects: 100% (49/49), done.
From https://gerrit.googlesource.com/git-repo
   fb527e3..c8290ad  master     -> origin/master

... A new repo command ( 1.25) is available.
... You should upgrade soon:

    cp /home/ssheikh/riscv-sifive/.repo/repo/repo /usr/bin/repo

Get git://github.com/sifive/meta-sifive
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 104 (delta 26), reused 93 (delta 17), pack-reused 0
Receiving objects: 100% (104/104), 43.46 KiB | 21.73 MiB/s, done.
Resolving deltas: 100% (26/26), done.
From git://github.com/sifive/meta-sifive
 * [new tag]         v201908        -> v201908
 * [new branch]      master         -> origin/master
 * [new branch]      v201908-branch -> origin/v201908-branch

Traceback (most recent call last):
  File "/home/ssheikh/riscv-sifive/.repo/repo/main.py", line 572, in <module>
    _Main(sys.argv[1:])
  File "/home/ssheikh/riscv-sifive/.repo/repo/main.py", line 547, in _Main
    result = run()
  File "/home/ssheikh/riscv-sifive/.repo/repo/main.py", line 540, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/ssheikh/riscv-sifive/.repo/repo/main.py", line 201, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/ssheikh/riscv-sifive/.repo/repo/subcmds/init.py", line 456, in Execute
    self._ConfigureUser()
  File "/home/ssheikh/riscv-sifive/.repo/repo/subcmds/init.py", line 347, in _ConfigureUser
    name  = self._Prompt('Your Name', mp.UserName)
  File "/home/ssheikh/riscv-sifive/.repo/repo/project.py", line 906, in UserName
    self._LoadUserIdentity()
  File "/home/ssheikh/riscv-sifive/.repo/repo/project.py", line 919, in _LoadUserIdentity
    u = self.bare_git.var('GIT_COMMITTER_IDENT')
  File "/home/ssheikh/riscv-sifive/.repo/repo/project.py", line 2988, in runner
    (self._project.name, name, p.stderr))
error.GitError: manifests var:
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <ssheikh@gs66-msagpc4.ndc.nasa.gov>) not allowed

 (I was successfully able to run the two make commands for creating an SOC on VC707 in the ubuntu app and run vivado to create the VC707 mcs file) and now and attempting to try to create a linux image for the SD card for the board.

**Comment by salmansheikh** [comment]
Never mind once I ran that repo command and the git config commands I got it. Yeah!
